services:
  nginx:
    image: localhost/nginx-ubi9:development
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "127.0.0.1:8080:8080"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m,mode=1777
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    stop_signal: SIGQUIT
